"use client";
import { useEffect, useMemo, useState } from "react";
import { modes } from "@/data/modes";
import { deepCopy } from "@/data/moments";
import { AppData, ModeId, Moment, PauseType } from "@/lib/types";
import { complete, completeWithChoice, defaults, loadData, saveData, weeklyCount } from "@/lib/storage";
import { chooseMoment } from "@/lib/selector";
type Screen="home"|"modes"|"pause"|"moment"|"deep"|"outcome"|"done"|"settings";
const sample=(a:string[])=>a[Math.floor(Math.random()*a.length)];
const choiceIcons=["🍎","🥣","💧","😌","🪑","🚶","↩️","✨"];
const outcomeChoices:Record<ModeId,Array<{icon:string;label:string}>>={
 eating:[{icon:"🍽️",label:"לאכול עכשיו"},{icon:"💧",label:"לשתות קודם"},{icon:"🚶",label:"לצאת לרגע"},{icon:"😌",label:"לקחת נשימה"},{icon:"🌿",label:"משהו אחר"}],
 lips:[{icon:"🫦",label:"להמשיך במה שעשיתי"},{icon:"💧",label:"למרוח לחות"},{icon:"✋",label:"לתת לידיים משהו אחר"},{icon:"😌",label:"לקחת נשימה"},{icon:"🌿",label:"משהו אחר"}],
 nails:[{icon:"✋",label:"להניח את הידיים"},{icon:"🖊️",label:"להחזיק חפץ אחר"},{icon:"🚶",label:"לשנות מקום"},{icon:"😌",label:"לקחת נשימה"},{icon:"🌿",label:"משהו אחר"}]
};
export default function App(){
 const [ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>("home"),[data,setData]=useState<AppData>(defaults),[mode,setMode]=useState<ModeId>(),[moment,setMoment]=useState<Moment>(),[step,setStep]=useState(0),[feedbackDone,setFeedbackDone]=useState(false),[action,setAction]=useState(""),[plannedChoice,setPlannedChoice]=useState<string>();
 const [deepLines,setDeepLines]=useState([deepCopy.seeing[0],deepCopy.allowing[0]]);
 useEffect(()=>{setData(loadData());setReady(true)},[]); useEffect(()=>{if(ready)saveData(data)},[data,ready]);
 const enabled=useMemo(()=>modes.filter(m=>data.enabledModes.includes(m.id)),[data.enabledModes]);
 const selectedMode=mode?modes.find(m=>m.id===mode):undefined;
 const count=weeklyCount(data); const countLabel=count===1?"השבוע יצרת רגע בחירה אחד.":`השבוע יצרת ${count} רגעי בחירה.`;
 const goHome=()=>{setScreen("home");setMode(undefined);setMoment(undefined);setStep(0);setFeedbackDone(false);setPlannedChoice(undefined)};
 const choose=(id:ModeId)=>{setMode(id);setScreen("pause")};
 const start=(kind:PauseType)=>{if(!mode)return;if(kind==="quick"){const m=chooseMoment(mode,data);setMoment(m);setData(d=>({...d,lastMomentId:m.id,feedback:{...d.feedback,[m.id]:{shown:(d.feedback[m.id]?.shown||0)+1,yes:d.feedback[m.id]?.yes||0,no:d.feedback[m.id]?.no||0}}}));setScreen("moment")}else{setDeepLines([sample(deepCopy.seeing),sample(deepCopy.allowing)]);setStep(0);setScreen("deep")}};
 const finish=()=>{if(!mode)return;setData(d=>complete(d,mode));setScreen("done");setTimeout(goHome,1500)};
 const confirmOutcome=(choice:string)=>{if(!mode)return;setData(d=>completeWithChoice(d,mode,choice));setScreen("done");setTimeout(goHome,1500)};
 const rate=(yes:boolean)=>{if(!moment||feedbackDone)return;setData(d=>{const f=d.feedback[moment.id]||{shown:1,yes:0,no:0};return {...d,feedback:{...d.feedback,[moment.id]:{...f,yes:f.yes+(yes?1:0),no:f.no+(yes?0:1)}}}});setFeedbackDone(true)};
 const toggle=(id:ModeId)=>setData(d=>{const has=d.enabledModes.includes(id);if(has&&d.enabledModes.length===1)return d;return {...d,enabledModes:has?d.enabledModes.filter(x=>x!==id):[...d.enabledModes,id]}});
 const addAction=()=>{const v=action.trim();if(!v)return;setData(d=>({...d,personalActions:[...d.personalActions,v]}));setAction("")};
 if(!ready)return <main className="shell"><section className="card"><p>רגע אחד…</p></section></main>;
 return <main className="shell"><section className="card screenFrame" key={screen} aria-live="polite">
  <header className="top"><button className="brand" onClick={goHome}>רגע אחד לעצמי</button>{screen!=="settings"&&<button className="iconButton" onClick={()=>setScreen("settings")} aria-label="הגדרות">⚙</button>}</header>
  {screen==="home"&&<div className="center intro"><span className="orb" aria-hidden="true">◌</span><h1>מה נכון עבורי עכשיו?</h1><p className="homeSubtitle">רגע אחד לעצמי</p><p className="introCopy">לפעמים אנחנו פועלים מתוך הרגל.<br/>אפשר לעצור לכמה שניות, לשים לב ולבחור איך להמשיך.</p>{count>0&&<p className="count">{countLabel}</p>}<button className="primary" onClick={()=>setScreen("modes")}>נעצור לרגע</button></div>}
  {screen==="modes"&&<div className="modeSelection"><Back onClick={goHome}/><p className="eyebrow">בחירה קטנה</p><h1>מה קורה עכשיו?</h1><p className="supportingText">אין צורך לבחור נכון. רק לבחור את מה שמתאר את הרגע.</p><div className="stack">{enabled.map(m=><button className="choice modeChoice" key={m.id} onClick={()=>choose(m.id)}><span aria-hidden="true">{m.emoji}</span><span className="choiceLabel">{m.label}</span></button>)}</div></div>}
  {screen==="pause"&&<div><Back onClick={()=>setScreen("modes")}/><ModeMarker mode={selectedMode}/><p className="eyebrow">כמה זמן מתאים עכשיו?</p><h1>איך נרצה לעצור?</h1><div className="stack"><button className="choice pause" onClick={()=>start("quick")}><b>יש לי עכשיו רגע כזה</b><small>רגע קצר אחד · 5–10 שניות</small></button><button className="choice pause" onClick={()=>start("deep")}><b>יש לי רגע לעצמי</b><small>לראות ← לתת מקום ← לבחור</small></button></div></div>}
  {screen==="moment"&&moment&&<div className="center moment"><Back onClick={()=>setScreen("pause")}/><ModeMarker mode={selectedMode}/><p className="eyebrow">רגע קצר</p><h1>{moment.title}</h1><p>{moment.text}</p><div className="feedback"><span>זה קצת עזר?</span><button onClick={()=>rate(true)} aria-pressed={feedbackDone}>👍 כן</button><button onClick={()=>rate(false)} aria-pressed={feedbackDone}>👎 לא כל כך</button></div><button className="primary" onClick={finish}>{moment.actionLabel}</button></div>}
  {screen==="deep"&&mode&&<div><Back onClick={()=>setScreen("pause")}/><ModeMarker mode={selectedMode}/><p className="eyebrow">{step+1} מתוך 3</p><div className="progress"><i style={{width:`${(step+1)*33.34}%`}}/></div>{step===0&&<><h1>לראות</h1><p className="lead">{deepLines[0]}</p><button className="primary" onClick={()=>setStep(1)}>הלאה</button></>}{step===1&&<><h1>לתת מקום</h1><p className="lead">{deepLines[1]}</p><button className="primary" onClick={()=>setStep(2)}>עוד רגע</button></>}{step===2&&<><h1>לבחור</h1><p className="choiceIntro">אין כאן תשובה נכונה אחת. הבחירה שייכת לך.</p><div className="options choiceCards">{[...deepCopy.choices,...data.personalActions].map((x,i)=><button className={plannedChoice===x?"selected":""} aria-pressed={plannedChoice===x} key={x} onClick={()=>setPlannedChoice(x)}><span aria-hidden="true">{choiceIcons[i%choiceIcons.length]}</span><b>{x}</b></button>)}</div><button className="primary" onClick={()=>setScreen("outcome")}>בחרתי איך להמשיך</button><button className="secondary" onClick={()=>setDeepLines([sample(deepCopy.seeing),sample(deepCopy.allowing)])}>הציעו לי אפשרות אחרת</button></>}</div>}
  {screen==="outcome"&&mode&&<div className="outcome"><Back onClick={()=>setScreen("deep")}/><ModeMarker mode={selectedMode}/><h1>ומה בחרת לעשות?</h1><p className="supportingText">אין תשובה נכונה.<br/>רק מה שבחרת ברגע הזה.</p><div className="outcomeCards">{outcomeChoices[mode].map(item=><button key={item.label} onClick={()=>confirmOutcome(item.label)}><span aria-hidden="true">{item.icon}</span><b>{item.label}</b></button>)}</div></div>}
  {screen==="done"&&<div className="center done"><ModeMarker mode={selectedMode}/><span className="doneIcon">🌱</span><h1>יצרת רגע קטן של בחירה</h1><p>לא משנה במה בחרת.<br/><br/>עצם זה שעצרת להיות לרגע עם עצמך —<br/>כבר נחשב.</p></div>}
  {screen==="settings"&&<div className="settings"><Back onClick={goHome}/><h1>הגדרות</h1><section className="settingsSection"><h2>מה יופיע עבורי?</h2><p className="sectionHint">אפשר לבחור אילו מצבים יוצגו במסך הבחירה.</p>{modes.map(m=><label className="toggle" key={m.id}><input type="checkbox" checked={data.enabledModes.includes(m.id)} onChange={()=>toggle(m.id)}/><span>{m.emoji} {m.label}</span></label>)}</section><section className="settingsSection"><h2>פעולות אישיות</h2><p className="sectionHint">פעולות שנוח לך לפגוש ברגע הבחירה.</p><div className="inputRow"><input value={action} onChange={e=>setAction(e.target.value)} placeholder="למשל: לצאת למרפסת" aria-label="פעולה אישית חדשה"/><button onClick={addAction}>שמירה</button></div>{data.personalActions.map((x,i)=><div className="saved" key={x+i}>{x}<button onClick={()=>setData(d=>({...d,personalActions:d.personalActions.filter((_,j)=>j!==i)}))} aria-label={`מחיקת ${x}`}>×</button></div>)}</section><section className="settingsSection settingsPrivacy"><div className="privacy"><b>הפרטיות שלך</b><p>כל הנתונים נשמרים בדפדפן הזה בלבד ואינם נשלחים לשום מקום.</p></div><button className="danger" onClick={()=>{if(confirm("למחוק את כל הנתונים המקומיים?")){localStorage.removeItem("right-for-me-now");setData(defaults);goHome()}}}>מחיקת כל הנתונים</button></section></div>}
 </section></main>
}
function Back({onClick}:{onClick:()=>void}){return <button className="back" onClick={onClick}>→ חזרה</button>}
function ModeMarker({mode}:{mode?:{emoji:string;id:ModeId}}){if(!mode)return null;const label={lips:"לשפתיים",nails:"לציפורניים",eating:"לאכילה"}[mode.id];return <div className="modeMarker" aria-label={`מצב: ${label}`}><span aria-hidden="true">{mode.emoji}</span><small>{label}</small></div>}
